;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="ActionNames.GravityGunTag",NewTagName="ActionNames.GravityGun")
GameplayTagRedirects=(OldTagName="ActionNames.ParryTag",NewTagName="ActionNames.Parry")
GameplayTagRedirects=(OldTagName="ActionNames.PrimaryFireTag",NewTagName="ActionNames.PrimaryFire")
GameplayTagRedirects=(OldTagName="ActionNames.SkillTag",NewTagName="ActionNames.Skill")
GameplayTagRedirects=(OldTagName="ActionNames.SprintTag",NewTagName="ActionNames.Sprint")
GameplayTagList=(Tag="Action.GravityGun",DevComment="")
GameplayTagList=(Tag="Action.Skill",DevComment="")
GameplayTagList=(Tag="Action.sprinting",DevComment="")
GameplayTagList=(Tag="ActionNames.AI.ProjectileAttack",DevComment="")
GameplayTagList=(Tag="ActionNames.EffectBurning",DevComment="")
GameplayTagList=(Tag="ActionNames.GravityGun",DevComment="")
GameplayTagList=(Tag="ActionNames.GravityGunThrow",DevComment="")
GameplayTagList=(Tag="ActionNames.GrowObject",DevComment="")
GameplayTagList=(Tag="ActionNames.Parry",DevComment="")
GameplayTagList=(Tag="ActionNames.PrimaryFire",DevComment="")
GameplayTagList=(Tag="ActionNames.ShrinkObject",DevComment="")
GameplayTagList=(Tag="ActionNames.Skill",DevComment="")
GameplayTagList=(Tag="ActionNames.Sprint",DevComment="")

